[platformio]
default_envs = seeed_xiao_esp32s3

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
build_flags =
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  https://github.com/greiman/SdFat.git
  https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3.git
  https://github.com/sparkfun/SparkFun_BMI270_Arduino_Library.git
  https://github.com/lewisxhe/PCF8563_Library.git
